import hre from "hardhat";
const { ethers } = hre;

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with:", deployer.address);

  // Deploy MockUSDC
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddr = await usdc.getAddress();
  console.log("MockUSDC:", usdcAddr);

  // Mint 100,000 USDC to deployer
  await (await usdc.mint(deployer.address, 100_000n * 10n**6n)).wait();
  console.log("Minted 100,000 USDC to deployer");

  // Deploy OPickFactory
  const Factory = await ethers.getContractFactory("OPickFactory");
  const factory = await Factory.deploy(usdcAddr);
  await factory.waitForDeployment();
  const factoryAddr = await factory.getAddress();
  console.log("OPickFactory:", factoryAddr);

  // Write config
  const fs = await import("fs");
  const configContent = `// Auto-generated by deploy script
export const CHAIN_ID = 31337;
export const RPC_URL = "http://127.0.0.1:8545";
export const USDC_ADDRESS = "${usdcAddr}";
export const FACTORY_ADDRESS = "${factoryAddr}";
export const DEPLOYER_ADDRESS = "${deployer.address}";
`;
  // Ensure frontend/src exists
  fs.mkdirSync(new URL("../../frontend/src", import.meta.url), { recursive: true });
  // Write relative to project root
  const path = await import("path");
  const configPath = path.resolve(process.cwd(), "frontend/src/config.js");
  fs.writeFileSync(configPath, configContent);
  console.log("Config written to frontend/src/config.js");
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
